### Population Indicators Data Concatenation
#### Overview
This notebook combines multiple CSV files containing population indicators data into a single dataframe. The files contain data on population percentages, rural and urban population, and other demographic indicators.

#### Objectives
* Load multiple CSV files containing population indicators data
* Concatenate the dataframes vertically to create a single dataframe
* Save the concatenated dataframe to a new CSV file

#### Data Sources
* `%_female.csv`: percentage of female population
* `%_male.csv`: percentage of male population
* `%_rural.csv`: percentage of rural population
* `%_urban.csv`: percentage of urban population
* `female.csv`: female population data
* `male.csv`: male population data
* `largest_city.csv`: population of largest city
* `rural_population.csv`: rural population data
* `total_population.csv`: total population data
* `urban_population.csv`: urban population data

#### Required Libraries
pandas: for data manipulation and analysis

#### Notebook Structure
1. Load CSV files
2. Concatenate dataframes
3. Save concatenated dataframe to new CSV file

In [1]:
# Import the script
import sys
sys.path.append('../scripts')

import merge_csv as m

In [2]:
# Directory containing my csv file
csv_dir = '../data'

In [3]:
# List all csv files to merge
csv_files = ['%_female.csv', '%_male.csv', '%_rural.csv', '%_urban.csv', 'female.csv', 'male.csv', 
             'largest_city.csv', 'rural_population.csv', 'total_population.csv', 'urban_population.csv']

In [4]:
# Load CSV files
dataframes = m.load_csv_files(csv_dir, csv_files)

In [5]:
# Concat DataFrames
concat_df = m.concat_dataframes(dataframes)

In [11]:
import pandas as pd

# Set display options to show all columns
pd.set_option('display.max_columns', None)

# Assuming concat_df is your DataFrame
concat_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,50.858849,50.850191,50.845065,50.836016,50.826773,50.823381,50.825589,50.826585,50.834861,50.844429,50.862857,50.882413,50.892872,50.920576,50.967882,51.012106,51.059762,51.112015,51.158120,51.203109,51.245443,51.300029,51.316623,51.283702,51.245053,51.192655,51.131628,51.053530,50.966859,50.919562,50.949598,51.068313,51.203841,51.322554,51.448267,51.556132,51.643855,51.718830,51.790647,51.860891,51.928710,52.020597,52.114272,52.182824,52.252512,52.299355,52.314708,52.316943,52.320503,52.331371,52.305638,52.306295,52.373864,52.442652,52.515590,52.589275,52.657475,52.723376,52.787792,52.849439,52.890182,52.873650,52.864860,52.904203,NaN
1,Africa Eastern and Southern,AFE,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,50.387880,50.388814,50.391276,50.395656,50.400512,50.405510,50.410713,50.413312,50.413630,50.414998,50.423730,50.424335,50.411762,50.395608,50.373201,50.350121,50.335117,50.320733,50.310497,50.301375,50.249665,50.234107,50.292066,50.373230,50.476537,50.594967,50.651383,50.640337,50.645756,50.650867,50.644383,50.636029,50.655412,50.701783,50.741414,50.778877,50.819764,50.833589,50.825554,50.821628,50.808843,50.790463,50.772365,50.752424,50.731596,50.711651,50.690852,50.669994,50.651777,50.638232,50.624907,50.609573,50.593858,50.577372,50.559167,50.531940,50.518935,50.515859,50.504887,50.495993,50.486544,50.478916,50.472347,50.464214,NaN
2,Afghanistan,AFG,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,48.083054,48.165001,48.242372,48.315893,48.385273,48.450285,48.511803,48.570464,48.626005,48.677997,48.726701,48.772846,48.816351,48.856631,48.893531,48.927195,48.958030,48.985824,49.021606,49.078746,49.147412,49.216172,49.304377,49.403368,49.538809,49.710513,49.837794,49.915439,49.964655,49.981496,49.990753,49.996505,50.001845,49.987425,49.963240,49.939028,49.907191,49.873789,49.843320,49.811100,49.775111,49.740205,49.704418,49.669165,49.635085,49.604651,49.579549,49.550982,49.525460,49.505857,49.483708,49.467665,49.455577,49.442103,49.432135,49.423184,49.414608,49.419284,49.437209,49.455485,49.470944,49.488405,49.508722,49.527063,NaN
3,Africa Western and Central,AFW,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,50.179683,50.194408,50.203157,50.203679,50.204549,50.204173,50.200936,50.203165,50.209982,50.212982,50.206895,50.190393,50.171685,50.154084,50.137214,50.122838,50.111484,50.108052,50.112248,50.117189,50.121167,50.121837,50.121337,50.124192,50.119761,50.109138,50.101000,50.092365,50.078742,50.063588,50.052719,50.046197,50.040800,50.033299,50.025629,50.020582,50.017777,50.017201,50.013269,50.004903,49.996125,49.988018,49.976103,49.959575,49.943769,49.930303,49.916596,49.900686,49.884805,49.868708,49.853047,49.839934,49.829168,49.818650,49.807914,49.796591,49.783515,49.770292,49.758369,49.747269,49.738956,49.732453,49.725969,49.719851,NaN
4,Angola,AGO,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,49.843790,49.700946,49.673797,49.634980,49.576791,49.488336,49.364408,49.213634,49.061033,48.952953,48.979999,49.100274,49.215607,49.325563,49.429489,49.531610,49.633841,49.732098,49.824167,49.909713,49.989454,50.063008,50.130768,50.199861,50.270013,50.334076,50.391713,50.458259,50.529847,50.592299,50.650016,50.692752,50.728672,50.787160,50.851331,50.871566,50.858805,50.846357,50.843965,50.857152,50.867875,50.875299,50.879883,50.868815,50.849483,50.829190,50.809484,50.790696,50.770992,50.751441,50.733762,50.716821,50.701107,50.686262,50.671632,50.657496,50.642098,50.625719,50.611615,50.598879,50.588558,50.580794,50.572443,50.563065,NaN

In [12]:
# Save the concatenated DataFrame
output_file = '../data/concat_data.csv'
m.save_concat_dataframe(concat_df, output_file)

Concat data saved to ../data/concat_data.csv

### After this we are able to continue with concatenated data our analysis